package com.testx.web.api.selenium.restassured.qe.ui.enums;

public enum ApplicationInputs {
  CONTINUE_AS_GUEST("Continue as Guest"),
  SIGN_UP_NOW("Sign Up Now"),
  LOGIN("Login"),
  LOG_IN("Log In"),
  SIGN_IN("Sign In"),
  SIGN_UP("Sign Up"),
  SIGN_IN_HEADER("Sign In to Your Family Dollar Account"),
  SIGNUP_HEADER("Sign up for Family Dollar"),
  SIGNUP_SUB_TEXT("Already a Family Dollar member?"),
  FD_TIP("Did you know?"),
  SIGNUP_TIP_DESCRIPTION("You can now log in to Family Dollar using your existing account with DollarTree."),
  SHARE_MY_LOCATION("Share My Location"),
  ENTER_MY_ZIP_CODE("Enter my ZIP Code"),
  SKIP("Skip"),
  SET_LOCATION_SETTINGS("Set Location Settings"),
  ENABLE_NOTIFICATIONS("Enable Notifications"),
  BIOMETRIC_HEADING("Would you like to sign in faster using Face ID ?"),
  EXP("Exp"),
  NEXT("Next"),
  CANCEL("Cancel"),
  CONTINUE("Continue"),
  PASSWORD_MUST_CONTAIN("Password must contain:"),
  AT_LEAST_CHARACTER("At least 8 characters"),
  ALPHABETIC_CHARACTER("One uppercase alphabetic character"),
  ONE_NUMBER("One number (1, 2, 3, 4 ...)"),
  ONE_SPECIAL_CHARACTER("One special character (![]`@$%^&*()-_=+;:’,<.>/?)"),
  NEWS_AND_PROMOTIONS_EMAIL("I want to receive news and promotions emails from Family Dollar"),
  I_AGREE_TO_THE_FOLLOWING("I agree to the following: "),
  PRIVACY_POLICY_COMMA("Privacy Policy,"),
  TERMS_AND_CONDITIONS_COMMA("Terms & Conditions,"),
  AND(" and "),
  SMART_COUPONS_TERMS_AND_CONDITIONS("Smart Coupons Terms & Conditions"),
  FAMILY_DOLLAR_EMPLOYEE("I am a Family Dollar employee"),
  EMPLOYEE_ID("Employee ID#"),
  CREATE_ACCOUNT("Create Account"),
  CREATE_ONE("Don’t have an account? Create one"),
  FORGOT_PASSWORD("Forgot Password?"),
  TRENDING_SEARCH("Trending Searches"),
  PREVIOUSLY_SEARCHED("Previously Searched"),
  CLEAR("Clear"),
  CART("Cart"),
  SCAN_PRODUCT_BARCODE("Scan Product Barcode"),
  SCAN_IN_STORE_PRODUCTS("Scan In-Store Products"),
  NO_COUPONS_FOUND("No Coupons Found"),
  SIGN_IN_TO_CLIP_COUPON("Sign In to Clip Coupon"),
  CLIP_COUPON("Clip Coupon"),
  NO_STORE_SELECTED("No Store Selected"),
  YOUR_STORE("Your Store"),
  SELECT_A_STORE("Select a Store"),
  CHANGE("Change"),
  SELECT_A_STORE_DESCRIPTION("to browse weekly ads and books."),
  TOP_CATEGORIES("Top Categories"),
  EXPLORE_ALL_PRODUCT_CATEGORIES("Explore All Product Categories"),
  EXPLORE_ALL_COUPON_CATEGORIES("Explore All Coupon Categories"),
  EXPLORE_COUPON_CATEGORIES("Explore Coupon Categories"),
  EXPLORE_PRODUCT_CATEGORIES("Explore Product Categories"),
  EXPLORE_ALL_CATEGORIES("Explore All Categories"),
  WELCOME_AUTUMN("Welcome Autumn"),
  ACCOUNT_SETTINGS("Account Settings"),
  PERSONAL_CONTACT("Personal and Contact Information"),
  EDIT("Edit"),
  YOUR_PROFILE("Your Profile"),
  PERSONAL_INFO("Personal Information"),
  NAME("Name"),
  DATE_OF_BIRTH("Date of Birth"),
  ZIP_CODE("ZIP Code"),
  ZIP_CODE_SIGNUP("Zip Code"),
  PASSWORD("Password"),
  CONTACT_INFORMATION("Contact Information"),
  EMAIL("Email"),
  PHONE_NUMBER("Phone Number"),
  FD_EMPLOYEE("Are you a Family Dollar Employee?"),
  ASSOCIATE_ID_NUMBER("Add your Associate Id Number"),
  COMMUNICATIONS("Communications"),
  PUSH_NOTIFICATION("Push Notifications"),
  NOTIFICATION_DESC("Enable push notifications to receive updates and deals directly on your device"),
  EMAIL_UPDATES("Email Updates"),
  EMAIL_UPDATES_DESC("Receive Family Dollar deals and promotions by email"),
  TEXT_NOTIFICATION("Text Notifications"),
  TEXT_NOTIFICATION_DESC("By toggling to “on,” I agree to receive marketing SMS/text messages from Family Dollar, including shopping cart reminders. I agree to the Privacy Policy and Text Messaging Terms & Conditions. Messages may be sent via autodialer. Consent not required for purchase; message frequency varies; message and data rates may apply. Text “HELP” for help, “STOP” to cancel."),
  MOBILE_TEXT_COMM("Mobile Text Communications"),
  MOBILE_TEXT_MESSAGE("Enable text notifications for order updates, deals and promotions"),
  MOBILE_SMS_HEADER("Mobile SMS Communications"),
  APP_SETTINGS("App Settings"),
  BIOMETRICS("Biometrics"),
  FACE_ID("Face ID"),
  BIOMETRICS_DESC("Quickly and securely access your account using your device's facial recognition feature"),
  APP_PERMISSIONS("App Permissions"),
  APP_PERMISSIONS_DESC("Adjust your device’s permissions for the Family Dollar app"),
  SUPPORTING_TEXT("Order confirmation and updates will be emailed to"),
  SUPPORT("Support"),
  SUPPORT_AND_SETTINGS("Support and Settings"),
  HELP("Help"),
  DELETE_ACCOUNT("Delete Account"),
  LEGAL("Legal"),
  PRIVACY_POLICY("Privacy Policy"),
  TERMS_AND_CONDITIONS("Terms & Conditions"),
  SMART_COUPONS_TERMS("Smart Coupons® Terms"),
  COUPON_POLICY("Coupon Policy"),
  CALIFORNIA_INFORMATION("California Information Sharing Disclosure"),
  CONTACT_US("Contact Us"),
  FAQS("FAQs"),
  VISIT_SITE("Visit Site"),
  FACEBOOK("Facebook"),
  FACEBOOK_HEADER("facebook"),
  INSTAGRAM("Instagram"),
  X("X"),
  TIKTOK("TikTok"),
  PINTEREST("Pinterest"),
  PINTEREST_APP("Pinterest App"),
  MESSAGES("Messages"),
  FIRST_NAME("First Name"),
  LAST_NAME("Last Name"),
  TURN_ON_BIOMETRICS("Turn on Biometrics"),
  NOT_NOW("Not Now"),
  START_SAVING("Start Saving"),
  VERIFICATION_CODE("Enter Your Verification Code"),
  PROFILE("Profile"),
  ACCOUNT("Account"),
  ADS_AND_BOOKS("Ads and Books"),
  FOR_YOUR_STORE("For Your Store"),
  DELETE_YOUR_ACCOUNT("Delete Your Account"),
  DELETE_MY_ACCOUNT("Delete My Account"),
  KEEP_MY_ACCOUNT("Keep My Account"),
  DELETE_ACCOUNT_CONFIRMATION("Are you sure you want to delete your Family Dollar account?"),
  RESET_YOUR_PASSWORD("Reset Your Password"),
  RESET_PASSWORD_BODY("Please enter your email address."),
  REMEMBER_YOUR_PASSWORD("Remember your password?"),
  SEND_ME_A_RECOVERY_LINK("Send Me a Recovery Link"),
  REDEEM_COUPONS("Redeem Coupons"),
  LIFETIME_SAVINGS("Lifetime Savings"),
  YOUR_DIGITAL_ID("Your Digital ID"),
  COUPONS_CLIPPED("Coupons Clipped"),
  COUPON_CLIPPED("Coupon Clipped"),
  FOR_YOU("For You"),
  BROWSE("Browse"),
  TRENDING("Trending"),
  TRENDING_SMART_COUPONS("Trending Smart Coupons"),
  EXPLORE_ALL("Explore All"),
  VIEW_ALL("View All"),
  ALL("All"),
  OUT_OF_STOCK("Out of Stock"),
  SMART_COUPONS_FOR_YOU("Smart Coupons® for You"),
  SMART_COUPONS_FOR_YOU_COUPON_PAGE("Smart Coupons® For You"),
  SEARCH_PRODUCTS_AND_COUPONS("Search Products and Coupons"),
  RECOMMENDED("Recommended"),
  SEARCH_FOR_COUPONS("Search for Coupons"),
  INFO_ICON_TOOLTIP("Savings can take a few days \n" + "to reflect the current total."),
  BARCODE_INSTRUCTION_TEXT("Show this barcode at checkout to get your coupon savings."),
  ALL_SUGGESTED_COUPONS_FOR_YOU("All Suggested Coupons For You");

  private final String enumValue;

  ApplicationInputs(String value) {
    this.enumValue = value;
  }

  public String getValue() {
    return this.enumValue;
  }
}
